dataInfo:

  camera:
    color:
      names: []
      parentFrames: []
      topics: []
      configTopics: []
    depth:
      names: []
      parentFrames: []
      topics: []
      configTopics: []
    pointCloud:
      names: []
      parentFrames: []
      topics: []
      configTopics: []
      maxDistances: []
      downSizes: []

  arm:
    jointState:
      names: []
      topics: []
    endPose:
      names: []
      topics: []
      orients: []

  localization:
    pose:
      names: ['pika_l', 'pika_r']
      topics: ['/pika_pose_l', '/pika_pose_r']

  gripper:
    encoder:
      names: ['pika_l', 'pika_r']
      topics: ['/gripper_l/data', '/gripper_r/data']

  imu:
    9axis:
      names: []
      topics: []

  lidar:
    pointCloud:
      names: []
      topics: []
      xDistanceUppers: []
      xDistanceLowers: []
      yDistanceUppers: []
      yDistanceLowers: []
      zDistanceUppers: []
      zDistanceLowers: []
      downSizes: []

  robotBase:
    vel:
      names: []
      topics: []

  lift:
    motor:
      names: []
      topics: []
      pubTopics: []
  
  tf:
    transform:
      parentFrames: []
      childFrames: []
